MPESA_CONSUMER_KEY: 'KPujvELGlGOwAtoxwcBPRUB7JIUJsiTt'
MPESA_CONSUMER_SECRET: 'j4OApBLiF2FZh0c3'
MPESA_PASSKEY: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
MPESA_SHORTCODE: '174379'
MPESA_INITIATOR_NAME: 'testapi'
MPESA_INITIATOR_PASSWORD: 'MTc0Mzc5YmZiMjc5ZjlhYTliZGJjZjE1OGU5N2RkNzFhNDY3Y2QyZTBjODkzMDU5YjEwZjc4ZTZiNzJhZGExZWQyYzkxOTIwMjMwMTEyMTgxMDEy'
CALLBACK_URL: 'https://d9af-105-161-114-112.eu.ngrok.io'
REGISTER_URL: "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl"